spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://127.0.0.1/sell22?characterEncoding=utf-8&useSSL=false
  jap:
    show-sql: true
  jackson:
    default-property-inclusion: non_null




server:
  context-path: /sell